const data = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "https://static.onecms.io/wp-content/uploads/sites/19/2008/10/23/MR_Reshoots_Evergreen_001-2000.jpg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "kabab",
    category: "lunch",
    price: 13.99,
    img: "https://hipersia.com/en/mi_ax/Original/1398/10/3719.jpg",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "milk shake",
    category: "shakes",
    price: 6.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToalH4zZSMMXx4I2_tF3_oTSsiWeFG-Txm8g&usqp=CAU",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "cheese sandwich",
    category: "breakfast",
    price: 20.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMtXYKotFw87ksRh6NxboH7W0-ntp7heAPqg&usqp=CAU",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "chicken salad",
    category: "lunch",
    price: 22.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEiH1ej78y_Jpq_r2_4IsUj82uFsUpNAMgvw&usqp=CAU",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "chocolate shake",
    category: "shakes",
    price: 18.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0vZsB7k9mSOpMwh4wV2vNHe-2-vjFh_n2EQ&usqp=CAU",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "egg overflow",
    category: "breakfast",
    price: 8.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmK8YIipu3bmPgoimjOuTZdCT2rMNh_mg1CQ&usqp=CAU",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, egg cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: " classic british fish and chips",
    category: "lunch",
    price: 12.99,
    img: "https://www.tastingtable.com/img/gallery/classic-british-fish-and-chips-recipe/l-intro-1670356962.jpg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNqh3CeTlgtp70XW4xpMtYkQrLPeoWscb6UF3gKG4bzC0Wh14hI5DEvZVIJ9ROTPF5tG8&usqp=CAU",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
]
export default data
